# i3blocks
# Autogenerated from man page /usr/share/man/man1/i3blocks.1.gz
complete -c i3blocks -s c --description 'Specifies an alternate configuration file path.'
complete -c i3blocks -s v --description 'Log level.  This option is cumulative.'
complete -c i3blocks -s V --description 'Print the version and exit.'

