# light
# Autogenerated from man page /usr/share/man/man1/light.1.gz
complete -c light -s H --description 'Show help text and exit.'
complete -c light -s V --description 'Show program version and exit.'
complete -c light -s L --description 'List available devices.'
complete -c light -s A --description 'Increase brightness by value.'
complete -c light -s U --description 'Decrease brightness by value.'
complete -c light -s S --description 'Set brightness to value.'
complete -c light -s G --description 'Get brightness, default.'
complete -c light -s N --description 'Set minimum brightness to value.'
complete -c light -s P --description 'Get minimum brightness.'
complete -c light -s I --description 'Save current brightness.'
complete -c light -s O --description 'Restore previously saved brightness El OPTIONS The behavior of the above comm…'
complete -c light -s r --description 'Interpret input and output values in raw mode.'
complete -c light -s s --description 'Specify device target path.   Use L to list available devices.'
complete -c light -s v --description 'Set verbosity level, by default light only outputs read values: Pp -tag -widt…'

